--this script drops the tables in the real estate database

DROP TABLE APPOINTMENT;

DROP TABLE PROPERTY;

DROP TABLE LISTING_AGENT;

DROP TABLE COUNTY;

DROP TABLE SCHOOL_DISTRICT;

DROP TABLE MUNICIPALITY;