--this script drops the database stored procedures

DROP PROCEDURE usp_CALC_PROP_TAX;

DROP PROCEDURE usp_DEL_APPOINTMENT;

DROP PROCEDURE usp_DEL_COUNTY;

DROP PROCEDURE usp_DEL_LISTING_AGENT;

DROP PROCEDURE usp_DEL_MUNICIPALITY;

DROP PROCEDURE usp_DEL_PROPERTY;

DROP PROCEDURE usp_DEL_SCHOOLDIST;

DROP PROCEDURE usp_INSERT_APPOINTMENT;

DROP PROCEDURE usp_INSERT_COUNTY;

DROP PROCEDURE usp_INSERT_LISTING_AGENT;

DROP PROCEDURE usp_INSERT_MUNICIPALITY;

DROP PROCEDURE usp_INSERT_PROPERTY;

DROP PROCEDURE usp_INSERT_SCHOOLDIST;

DROP PROCEDURE usp_UPDATE_AGENT_EMAIL;

DROP PROCEDURE usp_UPDATE_AGENT_PHONE;

DROP PROCEDURE usp_UPDATE_APPT_DATE_TIME;

DROP PROCEDURE usp_UPDATE_APPT_TIME;

DROP PROCEDURE usp_UPDATE_COUNTY_TAX;

DROP PROCEDURE usp_UPDATE_MUNI_TAX;

DROP PROCEDURE usp_UPDATE_PRICE;

DROP PROCEDURE usp_UPDATE_PROP_LISTING_AGENT;

DROP PROCEDURE usp_UPDATE_SCHOOL_TAX;